---
- name: Check ROS and upgrade if needed
  hosts: hostnames
  gather_facts: no
  strategy: free
  vars:
# I recommend setting the timeout to two minutes or even longer depending on how long it takes the device to pull the file.
    ansible_command_timeout: 390
    ansible_ssh_user: usernameofmikrotik

  roles:
    - mtk-ros-upgrade

- name: Check routerboard firmware and upgrade if needed
  hosts: hostnames
  gather_facts: false
  vars:
    ansible_ssh_user: usernameofmikrotik

  roles:
    - mtk-firmware-upgrade
